server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: "{cipher}3c4e4d579c93503b8d9a8d46b009d9c2943fa0049ad50721c38f7648d6d332ab

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  
eureka:
 instance:
   prefer-ip-address: true
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defailtZone: http://localhost:8761/eureka
