server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: murad@Kasif1234

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  
eureka:
 instance:
   prefer-ip-address: true
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defailtZone: http://localhost:8761/eureka
