server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: "{cipher}3c4e4d579c93503b8d9a8d46b009d9c2943fa0049ad50721c38f7648d6d332ab"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Hotel Service
    description: This service handles hotel management operations
    version: 1.0.0
  developer:
    name: Mohd Murad
    email: murad@example.com

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
