server:
  port: 8083


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: RATING-SERVICE
    description: This service handles ratings management operations
    version: 1.0.0
  developer:
    name: Mohd Murad
    email: murad@example.com

eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defailtZone: http://localhost:8761/eureka
